<a href="https://colab.research.google.com/github/sharvilpawar123-source/pandas-data-analysis/blob/main/pivotTableAndOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [7]:
data={
'Date': pd.date_range('2023-01-01', periods=20),
'Product': ['A', 'B', 'C', 'D'] * 5,
'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
           'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
'Sales': np.random.randint(100, 1000, 20),
'Units': np.random.randint(10, 100, 20),
'Rep': ['John', 'Mary', 'Bob', 'Alice', 'Bob', 'Alice', 'John', 'Mary','Bob',
        'John', 'Mary','John', 'Mary','Bob', 'Alice','Bob','John', 'Mary', 'Bob','Alice']
}

df = pd. DataFrame(data)
df ['Month'] = df ['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    200     53   John  January      Q1
1  2023-01-02       B   West    720     72   Mary  January      Q1
2  2023-01-03       C  North    699     23    Bob  January      Q1
3  2023-01-04       D  South    419     26  Alice  January      Q1
4  2023-01-05       A   East    654     89    Bob  January      Q1
5  2023-01-06       B   West    811     27  Alice  January      Q1
6  2023-01-07       C  North    495     72   John  January      Q1
7  2023-01-08       D  South    165     72   Mary  January      Q1
8  2023-01-09       A   East    206     66    Bob  January      Q1
9  2023-01-10       B   West    944     86   John  January      Q1
10 2023-01-11       C  North    231     66   Mary  January      Q1
11 2023-01-12       D  South    120     69   John  January      Q1
12 2023-01-13       A   East    722     71   Mary  January      Q1
13 2023-01-14       B   West    382     51    Bob  January      Q1
14 2023-01-15       C  North    825     96  Alice  January      Q1
15 2023-01-16       D  South    338     78    Bob  January      Q1
16 2023-01-17       A   East    721     26   John  January      Q1
17 2023-01-18       B   West    775     58   Mary  January      Q1
18 2023-01-19       C  North    384     72    Bob  January      Q1
19 2023-01-20       D  South    812     74  Alice  January      Q1

In [9]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product') # east with A ka mean
                                                                   # east not with A = NULL

Product      A      B      C      D
Region
East     500.6    NaN    NaN    NaN
North      NaN    NaN  526.8    NaN
South      NaN    NaN    NaN  370.8
West       NaN  726.4    NaN    NaN

In [11]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median') #used to make clustered heat map

Product      A      B      C      D
Region
East     654.0    NaN    NaN    NaN
North      NaN    NaN  495.0    NaN
South      NaN    NaN    NaN  338.0
West       NaN  775.0    NaN    NaN

In [13]:

pivot2= pd.pivot_table(df, values=['Sales', 'Units'], index='Region' ,columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     500.6    NaN    NaN    NaN  61.0   NaN   NaN   NaN
North      NaN    NaN  526.8    NaN   NaN   NaN  65.8   NaN
South      NaN    NaN    NaN  370.8   NaN   NaN   NaN  63.8
West       NaN  726.4    NaN    NaN   NaN  58.8   NaN   NaN

#CrossTabs - counting purpose

In [14]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

#Operations

In [32]:
df1=pd.DataFrame({
    "A": [1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
    })
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [33]:
df1.shape

(5, 3)

In [34]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [35]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [36]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [37]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#DataFrames Applying Function

In [38]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [39]:
# B change with its square val
def square(x):
  return x**2

In [40]:
df1['B'].apply(square) # apply ke andar esa fuct use bhejo jo aap use karna chah rahe ho to change val

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [41]:
#to apply it in main df1
df1['B']=df1['B'].apply(square)
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [42]:
df1['B']=df1['B'].apply(lambda x : x**2)
df1

   A        B    C
0  1    10000  100
1  2   160000  200
2  3   810000  300
3  4  2560000  400
4  5  6250000  500

#Finding Data

In [ ]:
#data can not come from numpy or pandas
#it comes from diff sources like CSV, xlx
#it is divided in row and col
#so we require to load CSV /xlx file

# CSV-Comma Separated Values - .CSV- pd.read_csv()
# Excel - .xlsx - pd.read_excel()
# JSON - .json - pd.read_json()
# HTML - .html- pd.read_html()
# and more

# kaggle
  # website where find lot of data
  # if u have to make ML based algorithm visit kaggle

  # kaggle-> datasets ->many data Bases